# site name
prefixName:
siteName: mrZ❤missY
# favicon and site master avatar
favicon: /img/favicon.ico
avatar: /img/zxyaily/food.jpg
url: https://www.zxyaily.top
description: 朝暮与岁月并往
cdn: https://cdn.jsdelivr.net/gh/Bierxiensi/CDN
#  https://cdn.jsdelivr.net/gh/Bierxiensi/Bierxiensi.github.io
#  https://cdn.jsdelivr.net/gh/honjun/cdn@1.6
pjax: 1
# 1开启
mathjax: 0

notice: 欢迎来到我们的博客！
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: {
    技术: {path: /categories/技术/, fa: fa-code },
    生活: {path: /categories/生活/, fa: fa-file-text-o },
    资源: {path: /categories/资源/, fa: fa-cloud-download },
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce },
    番组: {path: /bangumi/, fa: fa-film faa-vertical },
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  关于我们: { path: /, fa: fa-leaf faa-wrench , submenus: {
    时间轴: {path: /AboutUS/timebar/, fa: fa-meetup},
    大事记: {path: /AboutUS/events/, fa: iconfont icon-sakura },
    相册: {path: /album/, fa: fa-cogs },
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: {
    我？: {path: /about/, fa: fa-meetup},
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
   - https://cdn.jsdelivr.net/gh/Bierxiensi/CDN/img/mitaomao/cover/1.jpg
   - https://cdn.jsdelivr.net/gh/Bierxiensi/CDN/img/mitaomao/cover/2.jpg
   - https://cdn.jsdelivr.net/gh/Bierxiensi/CDN/img/mitaomao/cover/3.jpg
   - https://cdn.jsdelivr.net/gh/Bierxiensi/CDN/img/mitaomao/cover/5.jpg
   - https://cdn.jsdelivr.net/gh/Bierxiensi/CDN/img/mitaomao/cover/6.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash:
  - {title: yz, desc: 白桃, img: /img/mitaomao/StartDash/mitao1.jpg}
  - {title: zxyaily, desc: 我们的蜜桃屋, img: /img/mitaomao/StartDash/mitao3.jpg}
  - {title: xy, desc: 黑桃, img: /img/mitaomao/StartDash/mitao2.jpg}

#  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
#  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
#  - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}

# your site build time or founded date
siteBuildingTime: 10/20/2019

#social  url, img PC端配置
social:
  github: {url: http://github.com/bierxiensi, img: /img/social/github.png}
#  sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  wangyiyun: {url: /, img: /img/social/wangyiyun.png}
  zhihu: {url: /, img: /img/social/zhihu.png}
  email: {url: /, img: /img/social/email.png}
  csdn: {url: /, img: /img/social/csdn.png}
  mooc: {url: https://www.icourse163.org/home.htm?userId=1015405026#/home/course, img: /img/social/mooc.png}
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/bierxiensi, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal:
#    https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/alipay.jpg
  wechat: /img/custom/donate/wechat.jpg
  wechatSQ: /img/custom/donate/wechat.jpg
#  /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2

  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer:
  id: 2788116713
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: V1s6e4zjW3buOlz9EXT5P9aC-gzGzoHsz
v_appKey: CNNux6v8cGARzrfl3hqBeQ08

